apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #retain means dont delete data,    recycle-delete data dont delete disk, delete-delete disk
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0212954a2b2bcebee 

--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static 
spec: 

  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
     storage: 15Gi 
  storageClassName: ""
  volumeName: ebs-static

# --- 
# apiVersion: v1 
# kind: Pod 
# metadata: 
#   name: nginx 
# spec: 
#   containers: 
#   - name: nginx 
#     image: nginx 
#     volumeMounts: 
#     - name: nginx-html 
#       mountPath: /usr/share/nginx/html 
#   nodeSelector: 
#     topology.kubernetes.io/zone: us-east-1a
#   volumes: 
#     PersistentVolumeClaim: 
#       claimName: ebs-static
